'use client'
import { useCallback, useEffect, useState } from 'react'
import { useTranslations } from '@/lib/i18n'

type Cycle = { id:string;seasonId:string;seasonName:string;status:string;seasonPreparedAt?:string|null;previousSeasonId?:string|null;previousSeasonExpiredAt?:string|null }
type HistoryItem = { id:string;action:string;actorRole:string;createdAt:string }
type Bundle = { cycle:Cycle;history:HistoryItem[] }
type Season = { id:string;nom:string }
type WindowForm = { opensAt:string;closesAt:string }
type PrepareForm = { clubLicensing:WindowForm;personLicensing:WindowForm;registration:WindowForm;competitionEntry:WindowForm;financialCompliance:WindowForm;transferWindow:WindowForm }

const emptyWindow=():WindowForm=>({opensAt:'',closesAt:''})
const emptyPrepare=():PrepareForm=>({clubLicensing:emptyWindow(),personLicensing:emptyWindow(),registration:emptyWindow(),competitionEntry:emptyWindow(),financialCompliance:emptyWindow(),transferWindow:emptyWindow()})
const TEXT={
 fr:{title:'Renouvellement saisonnier',subtitle:'Préparez toutes les campagnes réglementaires avant activation de la saison.',create:'Créer un cycle',createTitle:'Nouveau cycle',season:'Saison',previousSeason:'Saison précédente (optionnel)',chooseSeason:'Choisir une saison',save:'Créer',cancel:'Annuler',loading:'Chargement…',empty:'Aucun cycle réglementaire.',status:'Statut',open:'Détail',close2:'Fermer',prepare:'Préparer la saison',prepared:'Préparation terminée',activate:'Activer',closeCycle:'Clôturer le cycle',history:'Historique',opensAt:'Ouverture',closesAt:'Fermeture',clubLicensing:'Licences clubs',personLicensing:'Licences individuelles',registration:'Inscriptions joueurs',competitionEntry:'Engagements compétitions',financialCompliance:'Conformité financière',transferWindow:'Fenêtre transferts SUMMER',previousExpired:'Licences saison précédente expirées le'},
 en:{title:'Season renewal',subtitle:'Prepare every regulatory campaign before activating the season.',create:'Create cycle',createTitle:'New cycle',season:'Season',previousSeason:'Previous season (optional)',chooseSeason:'Choose a season',save:'Create',cancel:'Cancel',loading:'Loading…',empty:'No regulatory cycle.',status:'Status',open:'Detail',close2:'Close',prepare:'Prepare season',prepared:'Preparation complete',activate:'Activate',closeCycle:'Close cycle',history:'History',opensAt:'Opens',closesAt:'Closes',clubLicensing:'Club licenses',personLicensing:'Individual licenses',registration:'Player registrations',competitionEntry:'Competition entries',financialCompliance:'Financial compliance',transferWindow:'SUMMER transfer window',previousExpired:'Previous season licenses expired on'},
 ar:{title:'تجديد الموسم',subtitle:'إعداد جميع الحملات التنظيمية قبل تفعيل الموسم.',create:'إنشاء دورة',createTitle:'دورة جديدة',season:'الموسم',previousSeason:'الموسم السابق (اختياري)',chooseSeason:'اختر موسما',save:'إنشاء',cancel:'إلغاء',loading:'جار التحميل…',empty:'لا توجد دورة تنظيمية.',status:'الحالة',open:'التفاصيل',close2:'إغلاق',prepare:'إعداد الموسم',prepared:'تم إعداد الموسم',activate:'تفعيل',closeCycle:'إغلاق الدورة',history:'السجل',opensAt:'الفتح',closesAt:'الإغلاق',clubLicensing:'تراخيص الأندية',personLicensing:'التراخيص الفردية',registration:'تسجيل اللاعبين',competitionEntry:'المشاركة في المسابقات',financialCompliance:'المطابقة المالية',transferWindow:'فترة الانتقالات الصيفية',previousExpired:'انتهت تراخيص الموسم السابق في'}
} as const

export default function AdminSeasonCyclesManager(){
 const {locale}=useTranslations();const text=TEXT[locale]
 const [cycles,setCycles]=useState<Cycle[]>([]);const [seasons,setSeasons]=useState<Season[]>([]);const [selected,setSelected]=useState<Bundle|null>(null)
 const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [creating,setCreating]=useState(false)
 const [form,setForm]=useState({seasonId:'',previousSeasonId:''});const [prepare,setPrepare]=useState<PrepareForm>(emptyPrepare())
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/admin/season-cycles',{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error??'Erreur');setCycles(b)}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setLoading(false)}},[])
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
 useEffect(()=>{void(async()=>{try{const r=await fetch('/api/admin/saisons',{cache:'no-store'});const b=await r.json();if(r.ok)setSeasons((Array.isArray(b)?b:[]).map((s:{id:string;nom:string})=>({id:s.id,nom:s.nom})))}catch{}})()},[])
 async function open(id:string){const r=await fetch(`/api/admin/season-cycles/${id}`,{cache:'no-store'});const b=await r.json();if(!r.ok)return setError(b.error??'Erreur');setSelected(b)}
 async function submitCreate(){if(!form.seasonId)return;setSaving(true);try{const r=await fetch('/api/admin/season-cycles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seasonId:form.seasonId,previousSeasonId:form.previousSeasonId||null})});const b=await r.json();if(!r.ok)throw new Error(b.error??'Erreur');setCreating(false);setForm({seasonId:'',previousSeasonId:''});await load()}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setSaving(false)}}
 async function callAction(path:string,body?:unknown){if(!selected)return;setSaving(true);try{const r=await fetch(`/api/admin/season-cycles/${selected.cycle.id}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body??{})});const b=await r.json();if(!r.ok)throw new Error(b.error??'Erreur');await Promise.all([load(),open(selected.cycle.id)])}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setSaving(false)}}
 function setWindow(name:keyof PrepareForm,field:keyof WindowForm,value:string){setPrepare(p=>({...p,[name]:{...p[name],[field]:value}}))}
 const labels:{name:keyof PrepareForm;label:string;requiredClose?:boolean}[]=[{name:'clubLicensing',label:text.clubLicensing},{name:'personLicensing',label:text.personLicensing},{name:'registration',label:text.registration},{name:'competitionEntry',label:text.competitionEntry},{name:'financialCompliance',label:text.financialCompliance},{name:'transferWindow',label:text.transferWindow,requiredClose:true}]
 const ready=labels.every(({name,requiredClose})=>prepare[name].opensAt&&(!requiredClose||prepare[name].closesAt))
 return <div className="container-fluid px-0 d-flex flex-column gap-4">
  <div className="d-flex justify-content-between align-items-start"><div><h1 className="h4 mb-1">{text.title}</h1><p className="text-muted mb-0">{text.subtitle}</p></div><button className="btn btn-primary" onClick={()=>setCreating(true)}>{text.create}</button></div>
  {error&&<div className="alert alert-danger" onClick={()=>setError(null)}>{error}</div>}
  {creating&&<div className="card border-primary"><div className="card-header"><strong>{text.createTitle}</strong></div><div className="card-body row g-2"><div className="col-md-6"><label className="form-label">{text.season}</label><select className="form-select" value={form.seasonId} onChange={e=>setForm({...form,seasonId:e.target.value})}><option value="">{text.chooseSeason}</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.nom}</option>)}</select></div><div className="col-md-6"><label className="form-label">{text.previousSeason}</label><select className="form-select" value={form.previousSeasonId} onChange={e=>setForm({...form,previousSeasonId:e.target.value})}><option value="">—</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.nom}</option>)}</select></div><div className="col-12 d-flex gap-2"><button disabled={saving} className="btn btn-primary" onClick={()=>void submitCreate()}>{text.save}</button><button className="btn btn-outline-secondary" onClick={()=>setCreating(false)}>{text.cancel}</button></div></div></div>}
  <div className="card border-0 shadow-sm"><div className="card-body p-0">{loading?<p className="p-4">{text.loading}</p>:cycles.length===0?<p className="p-4 text-muted">{text.empty}</p>:<div className="table-responsive"><table className="table align-middle mb-0"><thead><tr><th>{text.season}</th><th>{text.status}</th><th>{text.prepared}</th><th/></tr></thead><tbody>{cycles.map(c=><tr key={c.id}><td>{c.seasonName}</td><td><span className="badge bg-secondary">{c.status}</span></td><td>{c.seasonPreparedAt?new Date(c.seasonPreparedAt).toLocaleString():'—'}</td><td><button className="btn btn-sm btn-outline-primary" onClick={()=>void open(c.id)}>{text.open}</button></td></tr>)}</tbody></table></div>}</div></div>
  {selected&&<div className="card border-primary"><div className="card-header d-flex justify-content-between"><strong>{selected.cycle.seasonName}</strong><button className="btn-close" aria-label={text.close2} onClick={()=>setSelected(null)}/></div><div className="card-body d-flex flex-column gap-3">
    {selected.cycle.status==='DRAFT'&&!selected.cycle.seasonPreparedAt&&<div className="border rounded p-3"><h2 className="h6 mb-3">{text.prepare}</h2><div className="row g-3">{labels.map(({name,label,requiredClose})=><div className="col-12" key={name}><strong className="small">{label}</strong><div className="row g-2 mt-1"><div className="col-md-6"><label className="form-label small">{text.opensAt}</label><input type="datetime-local" className="form-control" value={prepare[name].opensAt} onChange={e=>setWindow(name,'opensAt',e.target.value)}/></div><div className="col-md-6"><label className="form-label small">{text.closesAt}{requiredClose?' *':''}</label><input type="datetime-local" className="form-control" value={prepare[name].closesAt} onChange={e=>setWindow(name,'closesAt',e.target.value)}/></div></div></div>)}</div><button disabled={saving||!ready} className="btn btn-primary mt-3" onClick={()=>void callAction('/prepare',prepare)}>{text.prepare}</button></div>}
    {selected.cycle.seasonPreparedAt&&<div className="alert alert-success mb-0">{text.prepared} · {new Date(selected.cycle.seasonPreparedAt).toLocaleString()}</div>}
    {selected.cycle.status==='DRAFT'&&<button disabled={saving||!selected.cycle.seasonPreparedAt} className="btn btn-success align-self-start" onClick={()=>void callAction('/activate')}>{text.activate}</button>}
    {selected.cycle.status==='ACTIVE'&&<button disabled={saving} className="btn btn-outline-danger align-self-start" onClick={()=>void callAction('/close')}>{text.closeCycle}</button>}
    {selected.cycle.previousSeasonExpiredAt&&<div className="alert alert-info">{text.previousExpired} {new Date(selected.cycle.previousSeasonExpiredAt).toLocaleString()}</div>}
    <div><h2 className="h6">{text.history}</h2>{selected.history.map(i=><div key={i.id} className="border-top py-2"><strong>{i.action}</strong> · {i.actorRole}</div>)}</div>
  </div></div>}
 </div>
}
