'use client'
import { useCallback,useEffect,useState } from 'react'
import { useTranslations } from '@/lib/i18n'

type Case={id:string;caseNumber:string;clubName?:string|null;clubId?:string|null;personType?:string|null;personId?:string|null;offenseType:string;description:string;status:string}
type Decision={id:string;summary:string;sanctionDescription?:string|null;suspensionId?:string|null;clubSanctionId?:string|null}
type Hearing={id:string;scheduledAt:string;location?:string|null}
type EventItem={id:string;action:string;actorRole:string;createdAt:string}
type Bundle={case:Case;hearings:Hearing[];decisions:Decision[];events:EventItem[];evidence:Array<{id:string;fileName:string;fileUrl:string}>}
type Team={id:string;nom:string}
const STATUSES=['OPEN','UNDER_REVIEW','HEARING_SCHEDULED','DECIDED','APPEALED','CLOSED']
const PERSON_TYPES=['','PLAYER','COACH','STAFF','REFEREE','AGENT','OTHER']
const SANCTION_TYPES=['TRANSFER_BAN','REGISTRATION_BAN','COMPETITION_BAN','FINE','POINT_DEDUCTION','MATCH_BEHIND_CLOSED_DOORS','STADIUM_SUSPENSION','COMPETITION_EXCLUSION','WARNING']
const TEXT={
 fr:{title:'Discipline fédérale',subtitle:'Les décisions individuelles créent désormais de vraies suspensions consommées par la feuille de match.',all:'Tous',status:'Statut',club:'Club',case:'Dossier',offense:'Infraction',open:'Détail',loading:'Chargement…',empty:'Aucun dossier.',create:'Ouvrir un dossier',chooseClub:'Club (optionnel)',personType:'Type de personne',personId:'ID personne',description:'Description',save:'Enregistrer',cancel:'Annuler',startReview:'Commencer l’examen',schedule:'Programmer audience',decide:'Rendre décision',close:'Clore',summary:'Résumé',sanction:'Description sanction',clubSanction:'Créer une sanction club',individual:'Créer une suspension joueur',matches:'Nombre de matchs',history:'Historique',decisions:'Décisions',hearings:'Audiences',evidence:'Pièces / preuves'},
 en:{title:'Federal discipline',subtitle:'Individual decisions now create real suspensions consumed by match operations.',all:'All',status:'Status',club:'Club',case:'Case',offense:'Offense',open:'Detail',loading:'Loading…',empty:'No case.',create:'Open case',chooseClub:'Club (optional)',personType:'Person type',personId:'Person ID',description:'Description',save:'Save',cancel:'Cancel',startReview:'Start review',schedule:'Schedule hearing',decide:'Issue decision',close:'Close',summary:'Summary',sanction:'Sanction description',clubSanction:'Create club sanction',individual:'Create player suspension',matches:'Matches',history:'History',decisions:'Decisions',hearings:'Hearings',evidence:'Evidence'},
 ar:{title:'الانضباط الفدرالي',subtitle:'القرارات الفردية تنشئ الآن إيقافات حقيقية تطبق في ورقة المباراة.',all:'الكل',status:'الحالة',club:'النادي',case:'الملف',offense:'المخالفة',open:'التفاصيل',loading:'جار التحميل…',empty:'لا يوجد ملف.',create:'فتح ملف',chooseClub:'النادي (اختياري)',personType:'نوع الشخص',personId:'معرف الشخص',description:'الوصف',save:'حفظ',cancel:'إلغاء',startReview:'بدء المراجعة',schedule:'برمجة جلسة',decide:'إصدار قرار',close:'إغلاق',summary:'ملخص',sanction:'وصف العقوبة',clubSanction:'إنشاء عقوبة للنادي',individual:'إنشاء إيقاف للاعب',matches:'عدد المباريات',history:'السجل',decisions:'القرارات',hearings:'الجلسات',evidence:'الوثائق / الأدلة'}
} as const

export default function AdminDisciplineManager(){
 const {locale}=useTranslations();const text=TEXT[locale]
 const [cases,setCases]=useState<Case[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [selected,setSelected]=useState<Bundle|null>(null);const [status,setStatus]=useState('')
 const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [creating,setCreating]=useState(false)
 const [form,setForm]=useState({clubId:'',personType:'',personId:'',offenseType:'',description:''});const [hearing,setHearing]=useState({scheduledAt:'',location:''});const [showHearing,setShowHearing]=useState(false)
 const [showDecision,setShowDecision]=useState(false);const [decision,setDecision]=useState({summary:'',sanctionDescription:'',withClubSanction:false,sanctionType:'WARNING',sanctionReason:'',startsAt:'',withSuspension:false,matchesCount:'1'})
 const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams();if(status)q.set('status',status);const r=await fetch(`/api/admin/discipline?${q}`,{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error??'Erreur');setCases(b)}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setLoading(false)}},[status])
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load])
 useEffect(()=>{void(async()=>{try{const r=await fetch('/api/admin/teams?team_type=club',{cache:'no-store'});const b=await r.json();if(r.ok)setTeams((Array.isArray(b)?b:b.teams??[]).map((x:{id:string;nom:string})=>({id:x.id,nom:x.nom})))}catch{}})()},[])
 async function open(id:string){const r=await fetch(`/api/admin/discipline/${id}`,{cache:'no-store'});const b=await r.json();if(!r.ok)return setError(b.error??'Erreur');setSelected(b)}
 async function action(name:string,payload:Record<string,unknown>={}){if(!selected)return;setSaving(true);try{const r=await fetch(`/api/admin/discipline/${selected.case.id}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error??'Erreur');await Promise.all([load(),open(selected.case.id)])}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setSaving(false)}}
 async function create(){if(!form.offenseType.trim()||!form.description.trim())return;setSaving(true);try{const r=await fetch('/api/admin/discipline',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,clubId:form.clubId||null,personType:form.personType||null,personId:form.personId||null})});const b=await r.json();if(!r.ok)throw new Error(b.error??'Erreur');setCreating(false);setForm({clubId:'',personType:'',personId:'',offenseType:'',description:''});await load()}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setSaving(false)}}
 async function decide(){if(!decision.summary.trim())return;const payload:Record<string,unknown>={summary:decision.summary,sanctionDescription:decision.sanctionDescription||null};if(decision.withClubSanction&&decision.sanctionReason&&decision.startsAt)payload.clubSanction={type:decision.sanctionType,reason:decision.sanctionReason,startsAt:decision.startsAt};if(decision.withSuspension)payload.individualSuspension={matchesCount:Number(decision.matchesCount)};await action('decision',payload);setShowDecision(false);setDecision({summary:'',sanctionDescription:'',withClubSanction:false,sanctionType:'WARNING',sanctionReason:'',startsAt:'',withSuspension:false,matchesCount:'1'})}
 return <div className="container-fluid px-0 d-flex flex-column gap-4">
  <div className="d-flex justify-content-between align-items-start"><div><h1 className="h4 mb-1">{text.title}</h1><p className="text-muted mb-0">{text.subtitle}</p></div><button className="btn btn-primary" onClick={()=>setCreating(true)}>{text.create}</button></div>
  {error&&<div className="alert alert-danger" onClick={()=>setError(null)}>{error}</div>}
  {creating&&<div className="card border-primary"><div className="card-body row g-2"><div className="col-md-4"><label className="form-label">{text.chooseClub}</label><select className="form-select" value={form.clubId} onChange={e=>setForm({...form,clubId:e.target.value})}><option value="">—</option>{teams.map(t=><option key={t.id} value={t.id}>{t.nom}</option>)}</select></div><div className="col-md-4"><label className="form-label">{text.personType}</label><select className="form-select" value={form.personType} onChange={e=>setForm({...form,personType:e.target.value})}>{PERSON_TYPES.map(p=><option key={p} value={p}>{p||'—'}</option>)}</select></div><div className="col-md-4"><label className="form-label">{text.personId}</label><input className="form-control" value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})}/></div><div className="col-md-4"><label className="form-label">{text.offense}</label><input className="form-control" value={form.offenseType} onChange={e=>setForm({...form,offenseType:e.target.value})}/></div><div className="col-12"><label className="form-label">{text.description}</label><textarea className="form-control" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="col-12 d-flex gap-2"><button className="btn btn-primary" disabled={saving} onClick={()=>void create()}>{text.save}</button><button className="btn btn-outline-secondary" onClick={()=>setCreating(false)}>{text.cancel}</button></div></div></div>}
  <div className="card border-0 shadow-sm"><div className="card-body"><select className="form-select" style={{maxWidth:280}} value={status} onChange={e=>setStatus(e.target.value)}><option value="">{text.all}</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div><div className="table-responsive"><table className="table mb-0"><thead><tr><th>{text.case}</th><th>{text.club}</th><th>{text.offense}</th><th>{text.status}</th><th/></tr></thead><tbody>{!loading&&cases.map(c=><tr key={c.id}><td>{c.caseNumber}</td><td>{c.clubName??'—'}</td><td>{c.offenseType}</td><td>{c.status}</td><td><button className="btn btn-sm btn-outline-primary" onClick={()=>void open(c.id)}>{text.open}</button></td></tr>)}</tbody></table>{loading&&<p className="p-3">{text.loading}</p>}{!loading&&!cases.length&&<p className="p-3 text-muted">{text.empty}</p>}</div></div>
  {selected&&<div className="card border-primary"><div className="card-header d-flex justify-content-between"><strong>{selected.case.caseNumber}</strong><button className="btn-close" onClick={()=>setSelected(null)}/></div><div className="card-body d-flex flex-column gap-3"><p>{selected.case.description}</p><div className="d-flex gap-2 flex-wrap">{selected.case.status==='OPEN'&&<button className="btn btn-outline-primary" onClick={()=>void action('start-review')}>{text.startReview}</button>}{selected.case.status==='UNDER_REVIEW'&&<button className="btn btn-outline-primary" onClick={()=>setShowHearing(true)}>{text.schedule}</button>}{['UNDER_REVIEW','HEARING_SCHEDULED'].includes(selected.case.status)&&<button className="btn btn-success" onClick={()=>setShowDecision(true)}>{text.decide}</button>}{selected.case.status==='DECIDED'&&<button className="btn btn-outline-secondary" onClick={()=>void action('close')}>{text.close}</button>}</div>
   {showHearing&&<div className="border rounded p-3 row g-2"><div className="col-md-6"><input type="datetime-local" className="form-control" value={hearing.scheduledAt} onChange={e=>setHearing({...hearing,scheduledAt:e.target.value})}/></div><div className="col-md-6"><input className="form-control" placeholder="Lieu" value={hearing.location} onChange={e=>setHearing({...hearing,location:e.target.value})}/></div><div className="col-12"><button className="btn btn-primary btn-sm" onClick={()=>void action('hearings',hearing).then(()=>setShowHearing(false))}>{text.save}</button></div></div>}
   {showDecision&&<div className="border rounded p-3 d-flex flex-column gap-2"><textarea className="form-control" placeholder={text.summary} value={decision.summary} onChange={e=>setDecision({...decision,summary:e.target.value})}/><textarea className="form-control" placeholder={text.sanction} value={decision.sanctionDescription} onChange={e=>setDecision({...decision,sanctionDescription:e.target.value})}/>{selected.case.clubId&&<label className="form-check"><input type="checkbox" className="form-check-input" checked={decision.withClubSanction} onChange={e=>setDecision({...decision,withClubSanction:e.target.checked})}/><span className="form-check-label">{text.clubSanction}</span></label>}{decision.withClubSanction&&<div className="row g-2"><div className="col-md-4"><select className="form-select" value={decision.sanctionType} onChange={e=>setDecision({...decision,sanctionType:e.target.value})}>{SANCTION_TYPES.map(s=><option key={s}>{s}</option>)}</select></div><div className="col-md-4"><input className="form-control" placeholder="Motif" value={decision.sanctionReason} onChange={e=>setDecision({...decision,sanctionReason:e.target.value})}/></div><div className="col-md-4"><input type="datetime-local" className="form-control" value={decision.startsAt} onChange={e=>setDecision({...decision,startsAt:e.target.value})}/></div></div>}{selected.case.personType==='PLAYER'&&selected.case.personId&&<label className="form-check"><input type="checkbox" className="form-check-input" checked={decision.withSuspension} onChange={e=>setDecision({...decision,withSuspension:e.target.checked})}/><span className="form-check-label">{text.individual}</span></label>}{decision.withSuspension&&<div style={{maxWidth:240}}><label className="form-label">{text.matches}</label><input type="number" min={1} max={99} className="form-control" value={decision.matchesCount} onChange={e=>setDecision({...decision,matchesCount:e.target.value})}/></div>}<div className="d-flex gap-2"><button className="btn btn-success" disabled={saving} onClick={()=>void decide()}>{text.decide}</button><button className="btn btn-outline-secondary" onClick={()=>setShowDecision(false)}>{text.cancel}</button></div></div>}
   <div><h2 className="h6">{text.evidence}</h2>{selected.evidence.length===0?<p className="text-muted small">—</p>:selected.evidence.map(e=><div className="border-top py-2" key={e.id}><a href={e.fileUrl} target="_blank" rel="noreferrer">{e.fileName}</a></div>)}</div>
   <div><h2 className="h6">{text.decisions}</h2>{selected.decisions.map(d=><div className="border-top py-2" key={d.id}><strong>{d.summary}</strong>{d.sanctionDescription&&<div>{d.sanctionDescription}</div>}{d.suspensionId&&<div className="small text-success">Suspension: {d.suspensionId}</div>}</div>)}</div><div><h2 className="h6">{text.hearings}</h2>{selected.hearings.map(h=><div className="border-top py-2" key={h.id}>{new Date(h.scheduledAt).toLocaleString()} {h.location??''}</div>)}</div><div><h2 className="h6">{text.history}</h2>{selected.events.map(e=><div className="border-top py-2" key={e.id}>{e.action} · {e.actorRole}</div>)}</div>
  </div></div>}
 </div>
}
