"use client";
import Link from "next/link";
import { useLanguage } from "@/lib/i18n/LanguageContext";
import { SheetStatusBadge } from "@/components/SheetStatusBadge";
import type { SheetStatus } from "@/entities/Sheet";

export function MatchOverviewHeader({ matchId, homeTeam, awayTeam, homeTeamAr, awayTeamAr, date, matchday, status, sheetStatus, officialsConfirmed }: { matchId:string; homeTeam:string; awayTeam:string; homeTeamAr:string|null; awayTeamAr:string|null; date:string|null; matchday:number|null; status:string; sheetStatus:SheetStatus; officialsConfirmed:boolean }) {
 const { lang, t }=useLanguage();
 const statusKeys={UPCOMING:"match.status.upcoming",IN_PROGRESS:"sheet.status.inProgress",FINISHED:"match.status.finished",CANCELLED:"match.status.cancelled"} as const;
 return <div className="card mb-4"><div className="card-body"><div className="d-flex justify-content-between align-items-start flex-wrap gap-3"><div><h2 className="h4 mb-1">{lang === "ar" && homeTeamAr ? homeTeamAr : homeTeam} <span className="text-muted">{t("match.versus")}</span> {lang === "ar" && awayTeamAr ? awayTeamAr : awayTeam}</h2><p className="text-muted mb-0">{date ? new Date(date).toLocaleString(lang==="ar"?"ar-TN":"fr-FR",{weekday:"long",day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}) : t("match.date.undefined")}{matchday ? ` — ${t("match.matchday",{number:matchday})}`:""}</p></div><div className="d-flex flex-column align-items-end gap-2"><span className="badge bg-info-subtle text-info">{status in statusKeys?t(statusKeys[status as keyof typeof statusKeys]):status}</span><SheetStatusBadge status={sheetStatus}/></div></div><div className="d-flex flex-wrap gap-2 mt-4"><Link href={`/${matchId}/officials`} className="btn btn-outline-primary">{t("officials.title")}{officialsConfirmed?<i className="bx bx-check-circle text-success ms-2"/>:<i className="bx bx-error text-warning ms-2"/>}</Link><Link href={`/${matchId}/controls`} className="btn btn-outline-primary">{t("controls.title")}</Link><Link href={`/${matchId}/pre-match`} className="btn btn-primary">{t("signatures.pre.title")}</Link><Link href={`/${matchId}/live`} className="btn btn-success">{t("navigation.liveSheet")}</Link><Link href={`/${matchId}/post-match`} className="btn btn-dark">{t("navigation.closure")}</Link></div></div></div>;
}
