/**
 * Utilitaires SEO pour ARBINOTE
 */

export const SEO_CONFIG = {
  siteName: 'ARBINOTE',
  baseUrl: process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000',
  defaultLocale: 'fr',
  supportedLocales: ['fr', 'en', 'ar'] as const,
  
  descriptions: {
    fr: 'ARBINOTE est la plateforme internationale de référence pour noter et comparer les arbitres de football de tous les championnats : calendrier, classements et votes en direct. Évaluez les performances des arbitres, consultez les statistiques et participez à la notation en temps réel.',
    en: 'ARBINOTE is the leading international platform to rate and compare football referees from all leagues worldwide: schedule, rankings and live votes. Evaluate referee performances, check statistics and participate in real-time rating.',
    ar: 'أربي نوت هي المنصة الدولية المرجعية لتقييم ومقارنة حكام كرة القدم من جميع البطولات حول العالم: جدول المباريات، التصنيفات والتصويت المباشر. قيّم أداء الحكام، راجع الإحصائيات وشارك في التقييم الفوري.',
  },
  
  keywords: {
    fr: [
      'ARBINOTE',
      'note arbitre',
      'notation arbitre',
      'évaluation arbitre',
      'classement arbitres',
      'notation arbitres',
      'vote arbitre',
      'statistiques arbitres',
      'performance arbitre',
      'arbitre football',
      'arbitrage football',
      'calendrier matchs',
      'résultats matchs',
      'meilleur arbitre',
      'classement officiel',
      'vote en direct',
      'notation en temps réel',
      'critères arbitrage',
      'VAR',
      'assistant arbitre',
      'décisions arbitrales',
      'football',
      'championnat',
      'ligue football',
      'arbitrage professionnel',
      'évaluation performance arbitre',
      'statistiques arbitrage',
      'classement international arbitres',
      'notation match',
      'vote match',
      'arbitrage mondial',
      'arbitres internationaux',
    ],
    en: [
      'ARBINOTE',
      'referee rating',
      'referee evaluation',
      'referee scoring',
      'referee rankings',
      'referee statistics',
      'referee performance',
      'football referee',
      'soccer referee',
      'match schedule',
      'match results',
      'best referee',
      'official rankings',
      'live voting',
      'real-time rating',
      'refereeing criteria',
      'VAR',
      'assistant referee',
      'refereeing decisions',
      'football',
      'soccer',
      'championship',
      'league',
      'professional refereeing',
      'referee performance evaluation',
      'refereeing statistics',
      'international referee rankings',
      'match rating',
      'match voting',
      'referee comparison',
      'worldwide refereeing',
      'international referees',
    ],
    ar: [
      'أربي نوت',
      'تقييم الحكام',
      'تقييم الحكم',
      'نقاط الحكم',
      'ترتيب الحكام',
      'إحصائيات الحكام',
      'أداء الحكم',
      'حكم كرة القدم',
      'التحكيم',
      'جدول المباريات',
      'نتائج المباريات',
      'أفضل حكم',
      'الترتيب الرسمي',
      'التصويت المباشر',
      'التقييم الفوري',
      'معايير التحكيم',
      'الفار',
      'الحكم المساعد',
      'قرارات التحكيم',
      'كرة القدم',
      'البطولة',
      'الدوري',
      'التحكيم الاحترافي',
      'تقييم أداء الحكم',
      'إحصائيات التحكيم',
      'ترتيب الحكام الدولي',
      'تقييم المباراة',
      'تصويت المباراة',
      'مقارنة الحكام',
      'التحكيم العالمي',
      'الحكام الدوليون',
    ],
  },
}

export function getSEOKeywords(locale: string): string[] {
  return SEO_CONFIG.keywords[locale as keyof typeof SEO_CONFIG.keywords] || SEO_CONFIG.keywords.fr
}

export function getSEODescription(locale: string): string {
  return SEO_CONFIG.descriptions[locale as keyof typeof SEO_CONFIG.descriptions] || SEO_CONFIG.descriptions.fr
}

