"use client";
import { useCallback,useEffect,useState } from "react";
type Entry={id:string;seasonId:string;status:string;documentsComplete:boolean;stadiumApprovalId?:string|null;financialComplianceId?:string|null;feesAmount?:string|null;feesPaymentId?:string|null;rejectionReason?:string|null};
type Edit={documentsComplete:boolean;stadiumApprovalId:string;financialComplianceId:string;feesPaymentId:string};
export default function CompetitionEntriesManager(){
 const [items,setItems]=useState<Entry[]>([]);const [form,setForm]=useState({seasonId:"",clubLicenseId:"",documentsComplete:false});const [edits,setEdits]=useState<Record<string,Edit>>({});const [error,setError]=useState("");const [saving,setSaving]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/admin/federation/competition-entries",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error??"Erreur");setItems(b);setEdits(Object.fromEntries((b as Entry[]).map(x=>[x.id,{documentsComplete:x.documentsComplete,stadiumApprovalId:x.stadiumApprovalId??"",financialComplianceId:x.financialComplianceId??"",feesPaymentId:x.feesPaymentId??""}])));},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{load().catch(e=>setError(e.message))},0);return()=>window.clearTimeout(timer)},[load]);
 async function create(){setSaving("create");try{const r=await fetch("/api/admin/federation/competition-entries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),b=await r.json();if(!r.ok)throw new Error(b.error??"Erreur");setForm({seasonId:"",clubLicenseId:"",documentsComplete:false});await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving("")}}
 async function persist(id:string,refresh=true){const e=edits[id];if(!e)throw new Error("Engagement introuvable");const r=await fetch(`/api/admin/federation/competition-entries/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({documentsComplete:e.documentsComplete,stadiumApprovalId:e.stadiumApprovalId||null,financialComplianceId:e.financialComplianceId||null,feesPaymentId:e.feesPaymentId||null})}),b=await r.json();if(!r.ok)throw new Error(b.error??"Erreur");if(refresh)await load()}
 async function save(id:string){setSaving(id);try{await persist(id)}catch(err){setError(err instanceof Error?err.message:"Erreur")}finally{setSaving("")}}
 async function submit(id:string){setSaving(id);try{await persist(id,false);const r=await fetch(`/api/admin/federation/competition-entries/${id}`,{method:"POST"}),b=await r.json();if(!r.ok)throw new Error(b.error??"Erreur");await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving("")}}
 function patch(id:string,value:Partial<Edit>){setEdits(p=>({...p,[id]:{...p[id],...value}}))}
 return <div className="container-fluid px-0 d-flex flex-column gap-3">
  <div><h1 className="h4">Engagements aux compétitions</h1><p className="text-muted">Les prérequis sont contrôlés dans leurs sources réelles au moment de l’approbation fédérale.</p></div>
  {error&&<div className="alert alert-danger" onClick={()=>setError("")}>{error}</div>}
  <div className="card border-0 shadow-sm"><div className="card-body row g-2"><div className="col-md-4"><input className="form-control" placeholder="Saison / compétition ID" value={form.seasonId} onChange={e=>setForm({...form,seasonId:e.target.value})}/></div><div className="col-md-4"><input className="form-control" placeholder="Licence club approuvée ID" value={form.clubLicenseId} onChange={e=>setForm({...form,clubLicenseId:e.target.value})}/></div><div className="col-md-2 form-check d-flex align-items-center gap-2"><input type="checkbox" checked={form.documentsComplete} onChange={e=>setForm({...form,documentsComplete:e.target.checked})}/><label>Dossier complet</label></div><div className="col-md-2"><button disabled={saving==="create"||!form.seasonId||!form.clubLicenseId} className="btn btn-primary w-100" onClick={()=>void create()}>Créer</button></div></div></div>
  {items.map(x=>{const e=edits[x.id]??{documentsComplete:x.documentsComplete,stadiumApprovalId:"",financialComplianceId:"",feesPaymentId:""};const editable=["DRAFT","CHANGES_REQUESTED"].includes(x.status);return <div className="card border-0 shadow-sm" key={x.id}><div className="card-header d-flex justify-content-between"><strong>{x.seasonId}</strong><span className="badge bg-secondary">{x.status}</span></div><div className="card-body row g-3"><div className="col-md-4"><label className="form-label">Homologation stade</label><input disabled={!editable} className="form-control" placeholder="stadiumInspectionId" value={e.stadiumApprovalId} onChange={ev=>patch(x.id,{stadiumApprovalId:ev.target.value})}/></div><div className="col-md-4"><label className="form-label">Conformité financière</label><input disabled={!editable} className="form-control" placeholder="financialComplianceId" value={e.financialComplianceId} onChange={ev=>patch(x.id,{financialComplianceId:ev.target.value})}/></div><div className="col-md-4"><label className="form-label">Paiement droits {x.feesAmount?`(${x.feesAmount} TND)`:''}</label><input disabled={!editable} className="form-control" placeholder="paymentId" value={e.feesPaymentId} onChange={ev=>patch(x.id,{feesPaymentId:ev.target.value})}/></div><div className="col-md-4 form-check ms-2"><input disabled={!editable} type="checkbox" className="form-check-input" checked={e.documentsComplete} onChange={ev=>patch(x.id,{documentsComplete:ev.target.checked})}/><label className="form-check-label">Dossier documentaire complet</label></div>{x.rejectionReason&&<div className="col-12 alert alert-warning mb-0">{x.rejectionReason}</div>}{editable&&<div className="col-12 d-flex gap-2"><button disabled={saving===x.id} className="btn btn-outline-primary" onClick={()=>void save(x.id)}>Enregistrer</button><button disabled={saving===x.id||!e.documentsComplete} className="btn btn-success" onClick={()=>void submit(x.id)}>Soumettre à la fédération</button></div>}</div></div>})}
 </div>
}
