import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { createStaffContractForClub, listStaffContractsForClub, listStaffContractOptionsForClub } from "@/services/StaffContractService";
import { STAFF_CONTRACT_ROLES, StaffContractWorkflowError, type StaffContractRole } from "../../../../../../../packages/regulatory-shared/src/staffContract";
export const runtime = "nodejs";
const canManage = (role: string) => role === "ADMIN" || role === "CLUB_ADMIN";
const actor = (request: NextRequest, user: { id: string; role: string }) => ({ userId: user.id, role: user.role, ipAddress: request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null, userAgent: request.headers.get("user-agent") });
function input(body: Record<string, unknown>) { return { staffId: String(body.staffId), seasonId: String(body.seasonId), role: body.role as StaffContractRole, startDate: String(body.startDate), endDate: String(body.endDate), salary: body.salary ? String(body.salary) : null, currency: body.currency ? String(body.currency) : null, qualificationId: body.qualificationId ? String(body.qualificationId) : null }; }
export async function GET() { const session = await auth(); if (!session?.user.teamId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const [contracts, options] = await Promise.all([listStaffContractsForClub(session.user.teamId), listStaffContractOptionsForClub(session.user.teamId)]); return NextResponse.json({ contracts, ...options, canManage: canManage(session.user.role) }); } catch (error) { console.error("Error loading staff contracts:", error); return NextResponse.json({ error: "Erreur lors du chargement des contrats staff" }, { status: 500 }); } }
export async function POST(request: NextRequest) { const session = await auth(); if (!session?.user.teamId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!canManage(session.user.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); try { const body = await request.json() as Record<string, unknown>; if (!body.staffId || !body.seasonId || !body.role || !body.startDate || !body.endDate || !STAFF_CONTRACT_ROLES.includes(body.role as StaffContractRole)) return NextResponse.json({ error: "Staff, saison, rôle et dates sont requis" }, { status: 400 }); return NextResponse.json(await createStaffContractForClub(session.user.teamId, input(body), actor(request, session.user)), { status: 201 }); } catch (error) { if (error instanceof StaffContractWorkflowError) return NextResponse.json({ error: error.message }, { status: 409 }); return NextResponse.json({ error: "Erreur serveur" }, { status: 500 }); } }
