export const dictionaries = {
 fr: {
  language:"Langue", adminNav:"Navigation admin", openMenu:"Ouvrir le menu", collapseMenu:"Réduire le menu", adminSpace:"Espace d’administration", administration:"Administration", logout:"Déconnexion",
  dashboards:"Tableaux de bord", dashboard:"Tableau de bord", apps:"Applications", pages:"Pages", stadiums:"Stades", players:"Joueurs", list:"Liste", add:"Ajouter", staff:"Staff", members:"Membres", matches:"Matchs", friendlyMatches:"Matchs amicaux", trainings:"Entraînements", trips:"Déplacements", tactics:"Planches tactiques", health:"Blessures & santé", discipline:"Discipline", cards:"Cartons", suspensions:"Suspensions", fines:"Amendes", notes:"Notes", audit:"Journal d’audit", exports:"Exports", settings:"Réglages", news:"Actualités", create:"Créer", media:"Médias", mediaItems:"Éléments média", galleries:"Galeries", callups:"Convocations", gallery:"Galerie", shop:"Boutique", products:"Produits", categories:"Catégories", ticketing:"Billetterie", perMatch:"Par match", ticketCategories:"Catégories de billets", sponsors:"Sponsors", communication:"Communication", club:"Le club", presentation:"Présentation", history:"Histoire", honors:"Palmarès", figures:"Grandes figures", academy:"Formation", editorial:"Contenu éditorial", academyApplications:"Candidatures académie", recruitment:"Recrutement", needs:"Postes recherchés", applications:"Candidatures", announcements:"Communiqués", contactSocial:"Contact & réseaux", socialNetworks:"Réseaux sociaux", contactDetails:"Coordonnées", receivedMessages:"Messages reçus", statistics:"Statistiques", playerStats:"Stats joueurs", users:"Utilisateurs", roles:"Rôles & permissions",
 contactTitle:"Contactez {team}", department:"Département", general:"Général", administrative:"Administratif", sport:"Sportif", partnerships:"Partenariats", subject:"Sujet", sendMessage:"Envoyer le message", fullName:"Nom et prénom", currentClub:"Club actuel", playerParentPhone:"Téléphone (joueur ou parent)", videoLink:"Lien vidéo (YouTube, Instagram...)",  close:"Fermer", send:"Envoyer", sending:"Envoi en cours...", firstName:"Prénom", lastName:"Nom", email:"Email", phone:"Téléphone", message:"Message", birthDate:"Date de naissance", category:"Catégorie", position:"Poste", choose:"Choisir...", optional:"facultatif", fileTypeError:"Type de fichier non autorisé.", fileTooLarge:"Le fichier est trop volumineux (5 Mo maximum).", submitError:"Une erreur est survenue lors de l’envoi.", child:"L’enfant", parent:"Le parent", parentName:"Nom du parent", document:"Photo ou document (facultatif)", sendApplication:"Envoyer la candidature", registerChild:"Inscrire mon enfant — {team}", registerHelp:"Rejoignez la formation du club. Remplissez ce formulaire, notre équipe vous recontactera pour organiser un essai.", recruitmentTitle:"Recrutement — {team}", recruitmentHelp:"Le club recrute des joueurs pour certaines catégories.", requestedPositions:"Postes recherchés", sendRecruitment:"Envoyer ma candidature", becomeSponsor:"Devenir sponsor de {team}", sponsorHelp:"Vous souhaitez soutenir le club et gagner en visibilité ? Remplissez ce formulaire, notre équipe étudiera votre demande.", companyName:"Nom de l’entreprise", contactName:"Nom du contact", website:"Site web", partnershipLevel:"Niveau de partenariat souhaité", companyLogo:"Logo de l’entreprise", logoPreview:"Aperçu du logo", logoSize:"Taille du logo fourni", companyPresentation:"Message / présentation de votre entreprise", sendSponsorRequest:"Envoyer ma demande de partenariat",
  installLabel:"Installer TeamManager", installMessage:"Installer TeamManager sur cet appareil pour un accès rapide.", later:"Plus tard", install:"Installer"
 },
 ar: {
  language:"اللغة", adminNav:"التنقل الإداري", openMenu:"فتح القائمة", collapseMenu:"طي القائمة", adminSpace:"فضاء الإدارة", administration:"الإدارة", logout:"تسجيل الخروج",
  dashboards:"لوحات القيادة", dashboard:"لوحة القيادة", apps:"التطبيقات", pages:"الصفحات", stadiums:"الملاعب", players:"اللاعبون", list:"القائمة", add:"إضافة", staff:"الإطار الفني والإداري", members:"الأعضاء", matches:"المباريات", friendlyMatches:"المباريات الودية", trainings:"التمارين", trips:"التنقلات", tactics:"الخطط التكتيكية", health:"الإصابات والصحة", discipline:"الانضباط", cards:"البطاقات", suspensions:"الإيقافات", fines:"الخطايا", notes:"الملاحظات", audit:"سجل التدقيق", exports:"التصدير", settings:"الإعدادات", news:"الأخبار", create:"إنشاء", media:"الوسائط", mediaItems:"عناصر الوسائط", galleries:"المعارض", callups:"الدعوات", gallery:"معرض الصور", shop:"المتجر", products:"المنتجات", categories:"الفئات", ticketing:"التذاكر", perMatch:"حسب المباراة", ticketCategories:"فئات التذاكر", sponsors:"الرعاة", communication:"التواصل", club:"النادي", presentation:"التقديم", history:"التاريخ", honors:"سجل الألقاب", figures:"أبرز الشخصيات", academy:"التكوين", editorial:"المحتوى التحريري", academyApplications:"طلبات الأكاديمية", recruitment:"الانتدابات", needs:"الخطط المطلوبة", applications:"الترشحات", announcements:"البلاغات", contactSocial:"الاتصال والشبكات", socialNetworks:"شبكات التواصل", contactDetails:"بيانات الاتصال", receivedMessages:"الرسائل الواردة", statistics:"الإحصائيات", playerStats:"إحصائيات اللاعبين", users:"المستخدمون", roles:"الأدوار والصلاحيات",
 contactTitle:"اتصل بـ {team}", department:"القسم", general:"عام", administrative:"إداري", sport:"رياضي", partnerships:"الشراكات", subject:"الموضوع", sendMessage:"إرسال الرسالة", fullName:"الاسم واللقب", currentClub:"النادي الحالي", playerParentPhone:"هاتف اللاعب أو الولي", videoLink:"رابط فيديو (YouTube، Instagram...)",  close:"إغلاق", send:"إرسال", sending:"جار الإرسال...", firstName:"الاسم", lastName:"اللقب", email:"البريد الإلكتروني", phone:"الهاتف", message:"الرسالة", birthDate:"تاريخ الميلاد", category:"الفئة", position:"الخطة", choose:"اختر...", optional:"اختياري", fileTypeError:"نوع الملف غير مسموح.", fileTooLarge:"حجم الملف كبير جدا (5 ميغابايت كحد أقصى).", submitError:"حدث خطأ أثناء الإرسال.", child:"الطفل", parent:"الولي", parentName:"اسم الولي", document:"صورة أو وثيقة (اختياري)", sendApplication:"إرسال الترشح", registerChild:"تسجيل طفلي — {team}", registerHelp:"انضم إلى مركز تكوين النادي. املأ الاستمارة وسيتصل بك فريقنا لتنظيم اختبار.", recruitmentTitle:"الانتدابات — {team}", recruitmentHelp:"ينتدب النادي لاعبين لبعض الفئات.", requestedPositions:"الخطط المطلوبة", sendRecruitment:"إرسال ترشحي", becomeSponsor:"كن راعيا لـ {team}", sponsorHelp:"هل ترغب في دعم النادي وتعزيز حضورك؟ املأ الاستمارة وسيدرس فريقنا طلب الشراكة.", companyName:"اسم المؤسسة", contactName:"اسم جهة الاتصال", website:"الموقع الإلكتروني", partnershipLevel:"مستوى الشراكة المطلوب", companyLogo:"شعار المؤسسة", logoPreview:"معاينة الشعار", logoSize:"حجم الشعار المقدم", companyPresentation:"رسالة / تقديم المؤسسة", sendSponsorRequest:"إرسال طلب الشراكة",
  installLabel:"تثبيت TeamManager", installMessage:"ثبّت TeamManager على هذا الجهاز للوصول السريع.", later:"لاحقا", install:"تثبيت"
 }
} as const;
export type TranslationKey=keyof typeof dictionaries.fr;
export function translate(locale:"fr"|"ar",key:TranslationKey,values?:Record<string,string|number>){let value:string=dictionaries[locale][key];for(const[k,v]of Object.entries(values??{}))value=value.replaceAll(`{${k}}`,String(v));return value;}
