import type { DataSource, EntityManager, SelectQueryBuilder } from 'typeorm'
import { isPersonLicenseActive } from '../../../packages/regulatory-shared/src/personLicensing'
import { assertStaffContractDates, assertStaffContractFederalTransition, assertStaffContractSubmittable, isStaffContractEligible, StaffContractWorkflowError, type StaffContractFederalStatus, type StaffContractStatus } from '../../../packages/regulatory-shared/src/staffContract'
import { canAccessFederation, canAccessLeague, canAccessPlatform } from './adminAuth'
import type { SsoUser } from './ssoSession'
import { PersonLicense, Saison, StaffContract, StaffContractDocument, StaffContractHistory, Team } from './entities'
import { notify } from './notificationClient'

export interface StaffContractAuditContext { userId: string; role: string; ipAddress?: string | null; userAgent?: string | null }
export interface StaffContractFilters { seasonId?: string; federationId?: string; leagueId?: string; clubId?: string; status?: StaffContractStatus; federalStatus?: StaffContractFederalStatus }
export class StaffContractAuthorizationError extends Error { constructor() { super('Forbidden'); this.name = 'StaffContractAuthorizationError' } }
function assertAccess(session: SsoUser, contract: StaffContract): void { if (canAccessPlatform(session) || canAccessFederation(session, contract.federationId) || (contract.leagueId && canAccessLeague(session, contract.leagueId, contract.federationId))) return; throw new StaffContractAuthorizationError() }
function applyScope(query: SelectQueryBuilder<StaffContract>, session: SsoUser): void { if (canAccessPlatform(session)) return; if (session.role === 'FEDERATION_ADMIN' && session.federationId) { query.andWhere('contract.federation_id = :federationId', { federationId: session.federationId }); return } if (session.role === 'LEAGUE_ADMIN' && session.leagueId) { query.andWhere('contract.league_id = :leagueId', { leagueId: session.leagueId }); return } query.andWhere('1 = 0') }

export async function listStaffContracts(dataSource: DataSource, session: SsoUser, filters: StaffContractFilters = {}) {
  const query = dataSource.getRepository(StaffContract).createQueryBuilder('contract').orderBy('contract.updated_at', 'DESC'); applyScope(query, session)
  if (filters.seasonId) query.andWhere('contract.season_id = :seasonId', { seasonId: filters.seasonId }); if (filters.federationId) query.andWhere('contract.federation_id = :filterFederationId', { filterFederationId: filters.federationId }); if (filters.leagueId) query.andWhere('contract.league_id = :filterLeagueId', { filterLeagueId: filters.leagueId }); if (filters.clubId) query.andWhere('contract.club_id = :clubId', { clubId: filters.clubId }); if (filters.status) query.andWhere('contract.status = :status', { status: filters.status }); if (filters.federalStatus) query.andWhere('contract.federation_status = :federalStatus', { federalStatus: filters.federalStatus })
  const contracts = await query.getMany(); const staffIds = [...new Set(contracts.map((item) => String(item.staffId)))]; const clubIds = [...new Set(contracts.map((item) => item.clubId))]; const seasonIds = [...new Set(contracts.map((item) => item.seasonId))]; const qualificationIds = contracts.flatMap((item) => item.qualificationId ? [item.qualificationId] : [])
  const [staffRows, clubs, seasons, qualifications] = await Promise.all([staffIds.length ? dataSource.query(`SELECT id, first_name_fr AS firstName, last_name_fr AS lastName FROM cms_staff WHERE id IN (${staffIds.map(() => '?').join(',')})`, staffIds) as Promise<Array<{ id: string; firstName: string; lastName: string }>> : [], clubIds.length ? dataSource.getRepository(Team).createQueryBuilder('club').where('club.id IN (:...ids)', { ids: clubIds }).getMany() : [], seasonIds.length ? dataSource.getRepository(Saison).createQueryBuilder('season').where('season.id IN (:...ids)', { ids: seasonIds }).getMany() : [], qualificationIds.length ? dataSource.getRepository(PersonLicense).createQueryBuilder('qualification').where('qualification.id IN (:...ids)', { ids: qualificationIds }).getMany() : []])
  const staffNames = new Map(staffRows.map((item) => [String(item.id), `${item.firstName} ${item.lastName}`])); const clubNames = new Map(clubs.map((item) => [item.id, item.nom])); const seasonMap = new Map(seasons.map((item) => [item.id, item])); const qualificationMap = new Map(qualifications.map((item) => [item.id, item]))
  return contracts.map((contract) => { const season = seasonMap.get(contract.seasonId); const qualification = contract.qualificationId ? qualificationMap.get(contract.qualificationId) : undefined; return Object.assign(contract, { staffName: staffNames.get(String(contract.staffId)) ?? String(contract.staffId), clubName: clubNames.get(contract.clubId) ?? contract.clubId, seasonName: season ? `${season.nom} · ${season.type_competition}` : contract.seasonId, requiresQualification: season?.requiresStaffQualification ?? false, qualificationNumber: qualification?.licenseNumber ?? null, qualificationActive: qualification ? isPersonLicenseActive(qualification.status, qualification.expiresAt) : false, eligible: isStaffContractEligible({ status: contract.status, federalStatus: contract.federationStatus, endDate: contract.endDate, requiresQualification: season?.requiresStaffQualification ?? false, qualificationStatus: qualification?.status, qualificationExpiresAt: qualification?.expiresAt }) }) })
}
export async function getStaffContractBundle(dataSource: DataSource, session: SsoUser, contractId: string) { const contract = await dataSource.getRepository(StaffContract).findOne({ where: { id: contractId } }); if (!contract) throw new StaffContractWorkflowError('Contrat staff introuvable'); assertAccess(session, contract); const [documents, events, rows] = await Promise.all([dataSource.getRepository(StaffContractDocument).find({ where: { contractId }, order: { version: 'DESC' } }), dataSource.getRepository(StaffContractHistory).find({ where: { contractId }, order: { createdAt: 'DESC' } }), listStaffContracts(dataSource, session, { clubId: contract.clubId, seasonId: contract.seasonId })]); return { contract: rows.find((item) => item.id === contractId) ?? contract, documents, history: events } }
async function saveHistory(manager: EntityManager, contractId: string, audit: StaffContractAuditContext, input: { action: string; fromStatus?: string | null; toStatus?: string | null; reason?: string | null; beforeValue?: Record<string, unknown> | null; afterValue?: Record<string, unknown> | null }): Promise<void> { const repo = manager.getRepository(StaffContractHistory); await repo.save(repo.create({ contractId, action: input.action, fromStatus: input.fromStatus ?? null, toStatus: input.toStatus ?? null, actorUserId: audit.userId, actorRole: audit.role, reason: input.reason ?? null, beforeValue: input.beforeValue ?? null, afterValue: input.afterValue ?? null, ipAddress: audit.ipAddress ?? null, userAgent: audit.userAgent ?? null })) }
export async function transitionStaffContract(dataSource: DataSource, session: SsoUser, audit: StaffContractAuditContext, contractId: string, targetStatus: StaffContractFederalStatus, reason?: string | null): Promise<StaffContract> {
  if (['REJECTED', 'CANCELLED'].includes(targetStatus) && !reason?.trim()) throw new StaffContractWorkflowError('Un motif est obligatoire pour cette décision')
  const updated = await dataSource.transaction(async (manager) => { const repo = manager.getRepository(StaffContract); const contract = await repo.createQueryBuilder('contract').setLock('pessimistic_write').where('contract.id = :contractId', { contractId }).getOne(); if (!contract) throw new StaffContractWorkflowError('Contrat staff introuvable'); assertAccess(session, contract); assertStaffContractFederalTransition(contract.federationStatus, targetStatus)
    if (targetStatus === 'UNDER_REVIEW' || targetStatus === 'APPROVED') { const document = await manager.getRepository(StaffContractDocument).findOne({ where: { contractId, status: 'CURRENT' } }); assertStaffContractSubmittable(contract.status, Boolean(document)); assertStaffContractDates(contract.startDate, contract.endDate); if (new Date(`${contract.endDate}T23:59:59.999Z`) < new Date()) throw new StaffContractWorkflowError('Un contrat expiré ne peut pas être homologué') }
    if (targetStatus === 'APPROVED') { const season = await manager.getRepository(Saison).findOne({ where: { id: contract.seasonId } }); if (!season) throw new StaffContractWorkflowError('Compétition-saison introuvable'); if (season.requiresStaffQualification) { if (!contract.qualificationId) throw new StaffContractWorkflowError('Une qualification technique valide est obligatoire'); const qualification = await manager.getRepository(PersonLicense).findOne({ where: { id: contract.qualificationId, clubId: contract.clubId, personReferenceId: String(contract.staffId), seasonId: contract.seasonId } }); if (!qualification || !['COACH', 'STAFF', 'MEDICAL', 'DIRECTOR'].includes(qualification.personType) || !isPersonLicenseActive(qualification.status, qualification.expiresAt)) throw new StaffContractWorkflowError("La qualification technique liée n'est pas active") } }
    const previous = contract.federationStatus; contract.federationStatus = targetStatus; contract.rejectionReason = targetStatus === 'REJECTED' || targetStatus === 'CANCELLED' ? reason!.trim() : null; if (targetStatus === 'UNDER_REVIEW') contract.reviewStartedAt = new Date(); if (targetStatus === 'APPROVED') { contract.approvedAt = new Date(); contract.approvedBy = audit.userId; contract.rejectedAt = null } if (targetStatus === 'REJECTED') { contract.rejectedAt = new Date(); contract.approvedAt = null; contract.approvedBy = null } await repo.save(contract); await saveHistory(manager, contractId, audit, { action: `FEDERAL_${targetStatus}`, fromStatus: previous, toStatus: targetStatus, reason, beforeValue: { federationStatus: previous }, afterValue: { federationStatus: targetStatus } }); return contract })
  const eventType: Partial<Record<StaffContractFederalStatus, string>> = { UNDER_REVIEW: 'STAFF_CONTRACT_UNDER_REVIEW', APPROVED: 'STAFF_CONTRACT_APPROVED', REJECTED: 'STAFF_CONTRACT_REJECTED', CANCELLED: 'STAFF_CONTRACT_CANCELLED' }; if (eventType[targetStatus]) await notify({ eventId: `staff-contract:${contractId}:${targetStatus}:${updated.updatedAt.toISOString()}`, type: eventType[targetStatus]!, target: { type: 'TEAM', teamId: updated.clubId }, teamId: updated.clubId, category: 'REGULATORY', title: 'Contrat staff', body: `Le contrat staff est maintenant au statut fédéral ${targetStatus}.`, data: { contractId, staffId: updated.staffId, federalStatus: targetStatus, reason: reason ?? null } }); return updated
}
