export const dictionaries = {
  fr: {
    selectMatch:"Sélectionnez un match", selectMatchHelp:"Choisissez un match dans la barre du bas pour ouvrir sa feuille.", noMatches:"Aucun match dans les prochains jours", matches:"Liste des matchs", dateUndefined:"Date non définie", vs:"vs", close:"Fermer", installLabel:"Installer MatchSheet", installMessage:"Installer MatchSheet sur cet appareil pour un accès rapide.", later:"Plus tard", install:"Installer", clear:"Effacer",
    lineupMissing:"Composition non renseignée (à faire depuis teamManager).", lineupMissingShort:"Composition non renseignée.", starters:"Titulaires", substitutes:"Remplaçants", controls:"Contrôles", controlsHelp:"Vérification des numéros de maillot et de l’identité", controlled:"{done}/{total} contrôlés", backSignatures:"Retour aux signatures", optionalNote:"Note (optionnel)", unknownPlayer:"Joueur inconnu",
    officials:"Infos arbitre", required:"Obligatoire", fullName:"Nom complet", license:"N° de licence",
    liveTitle:"Feuille de match en direct — enregistrez les événements au fil du jeu.", startMatch:"Démarrer le match", matchStarted:"Match démarré", period:"Temps :", cards:"Cartons", goals:"Buts", injuries:"Blessures", substitutions:"Remplacements", team:"Équipe", player:"Joueur", select:"— Sélectionner —", cardType:"Type de carton", minute:"Minute", reason:"Motif", noneSpecified:"— Aucun / non précisé —", commentOptional:"Commentaire (optionnel)", comment:"Commentaire", action:"Action", addCard:"Ajouter un carton", addGoal:"Ajouter un but", addInjury:"Ajouter une blessure", addSubstitution:"Ajouter un remplacement", unidentified:"— Non identifié —", scorer:"Buteur", details:"Détails", ownGoal:"CSC", penalty:"Penalty", periodOptional:"Temps (optionnel)", unspecified:"— Non précisé —", minuteOptional:"Minute (optionnel)", description:"Description", replacement:"Remplacement", yes:"Oui", no:"Non", playerOut:"Joueur sortant", playerIn:"Joueur entrant", change:"Changement", exits:"sort", enters:"entre", yellow:"Jaune", red:"Rouge", doubleYellow:"Double jaune", firstHalf:"1ère mi-temps", secondHalf:"2e mi-temps", extraTime1:"Prolongation 1", extraTime2:"Prolongation 2",
 confirmation:"Confirmation...", confirmAndStart:"Confirmer et passer au match", add:"Ajouter", closeSheet:"Clôturer la feuille de match", teamLabel:"Équipe {name}", upcoming:"À venir", finished:"Terminé", cancelled:"Annulé", matchday:"Journée {number}", liveSheet:"Feuille en direct", closure:"Clôture (signatures après-match)",    selectPlayer:"Merci de sélectionner un joueur", selectTeam:"Merci de sélectionner une équipe", selectBothPlayers:"Merci de sélectionner les deux joueurs", cardSaved:"Carton enregistré", goalSaved:"But enregistré", injurySaved:"Blessure enregistrée", substitutionSaved:"Remplacement enregistré", deleteCardConfirm:"Supprimer ce carton ?", deleteGoalConfirm:"Supprimer ce but ?", deleteInjuryConfirm:"Supprimer cette blessure ?", deleteSubstitutionConfirm:"Supprimer ce remplacement ?", addTheCard:"Ajouter le carton", addTheGoal:"Ajouter le but", addTheInjury:"Ajouter la blessure", addTheSubstitution:"Ajouter le remplacement", refereeCentral:"Arbitre central", assistant1:"Arbitre assistant 1", assistant2:"Arbitre assistant 2", fourthOfficial:"4ᵉ arbitre", delegate:"Délégué principal", officialsValid:"Les postes obligatoires sont validés.", officialsRequired:"Les postes obligatoires doivent être validés avant de confirmer l’avant-match.", officialNameRequired:"Le nom de l’officiel est requis.", validatedAgain:"Validé — revalider", save:"Enregistrer", validate:"Valider", confirmError:"Erreur lors de la confirmation.", addError:"Erreur lors de l’ajout.", deleteError:"Erreur lors de la suppression.", validationError:"Erreur lors de la validation.", closeSheetConfirm:"Clôturer la feuille de match ? Cette action est définitive.", closeError:"Erreur lors de la clôture.",
    draft:"Brouillon", preSigned:"Avant-match signé", inProgress:"Match en cours", postSigned:"Après-match signé", closed:"Feuille clôturée",
    preSignatures:"Signatures avant-match", postSignatures:"Signatures après-match", signaturesCompletePre:"Les 3 signatures avant-match ont été recueillies.", signaturesCompletePost:"Les 3 signatures après-match ont été recueillies.", preConfirmed:"Avant-match déjà confirmé", waitingSignatures:"En attente des 3 signatures avant de pouvoir démarrer le match.", reservationsPre:"Réserves avant-match", reservationsPost:"Réserves après-match", signFirst:"Veuillez signer dans le cadre avant de valider.", signatureSaved:"Signature enregistrée.", saveError:"Erreur lors de l’enregistrement.", signed:"Signé", signedOn:"Signé le {date}", signatureAlt:"Signature — {label}", edit:"Modifier", signerOptional:"Nom du signataire (optionnel)", cancel:"Annuler", saving:"Enregistrement...", validateSignature:"Valider la signature", unsigned:"Non signé.", reservationRequired:"Le contenu de la réserve est requis.", noReservation:"Aucune réserve enregistrée.", delete:"Supprimer", author:"Auteur", homeTeam:"Équipe domicile", awayTeam:"Équipe extérieure", referee:"Arbitre", reservationContent:"Contenu de la réserve",
  },
  ar: {
    selectMatch:"اختر مباراة", selectMatchHelp:"اختر مباراة من الشريط السفلي لفتح ورقتها.", noMatches:"لا توجد مباريات في الأيام القادمة", matches:"قائمة المباريات", dateUndefined:"التاريخ غير محدد", vs:"ضد", close:"إغلاق", installLabel:"تثبيت MatchSheet", installMessage:"ثبّت MatchSheet على هذا الجهاز للوصول السريع.", later:"لاحقا", install:"تثبيت", clear:"مسح",
    lineupMissing:"لم يتم إدخال التشكيلة (تُستكمل عبر teamManager).", lineupMissingShort:"لم يتم إدخال التشكيلة.", starters:"الأساسيون", substitutes:"البدلاء", controls:"التثبت", controlsHelp:"التحقق من أرقام القمصان والهوية", controlled:"تم التثبت من {done}/{total}", backSignatures:"العودة إلى الإمضاءات", optionalNote:"ملاحظة (اختياري)", unknownPlayer:"لاعب غير معروف",
    officials:"معلومات الحكام", required:"إجباري", fullName:"الاسم الكامل", license:"رقم الإجازة",
    liveTitle:"ورقة المباراة المباشرة — سجّل الأحداث أثناء اللعب.", startMatch:"بدء المباراة", matchStarted:"بدأت المباراة", period:"الفترة:", cards:"البطاقات", goals:"الأهداف", injuries:"الإصابات", substitutions:"التغييرات", team:"الفريق", player:"اللاعب", select:"— اختر —", cardType:"نوع البطاقة", minute:"الدقيقة", reason:"السبب", noneSpecified:"— لا شيء / غير محدد —", commentOptional:"تعليق (اختياري)", comment:"التعليق", action:"الإجراء", addCard:"إضافة بطاقة", addGoal:"إضافة هدف", addInjury:"إضافة إصابة", addSubstitution:"إضافة تغيير", unidentified:"— غير محدد —", scorer:"مسجل الهدف", details:"التفاصيل", ownGoal:"ضد مرماه", penalty:"ركلة جزاء", periodOptional:"الفترة (اختياري)", unspecified:"— غير محدد —", minuteOptional:"الدقيقة (اختياري)", description:"الوصف", replacement:"التغيير", yes:"نعم", no:"لا", playerOut:"اللاعب الخارج", playerIn:"اللاعب الداخل", change:"التغيير", exits:"يخرج", enters:"يدخل", yellow:"صفراء", red:"حمراء", doubleYellow:"إنذاران", firstHalf:"الشوط الأول", secondHalf:"الشوط الثاني", extraTime1:"الإضافي الأول", extraTime2:"الإضافي الثاني",
 confirmation:"جار التأكيد...", confirmAndStart:"التأكيد والانتقال إلى المباراة", add:"إضافة", closeSheet:"إغلاق ورقة المباراة", teamLabel:"فريق {name}", upcoming:"قادمة", finished:"انتهت", cancelled:"ملغاة", matchday:"الجولة {number}", liveSheet:"الورقة المباشرة", closure:"الإغلاق (إمضاءات ما بعد المباراة)",    selectPlayer:"يرجى اختيار لاعب", selectTeam:"يرجى اختيار فريق", selectBothPlayers:"يرجى اختيار اللاعبين", cardSaved:"تم حفظ البطاقة", goalSaved:"تم حفظ الهدف", injurySaved:"تم حفظ الإصابة", substitutionSaved:"تم حفظ التغيير", deleteCardConfirm:"حذف هذه البطاقة؟", deleteGoalConfirm:"حذف هذا الهدف؟", deleteInjuryConfirm:"حذف هذه الإصابة؟", deleteSubstitutionConfirm:"حذف هذا التغيير؟", addTheCard:"إضافة البطاقة", addTheGoal:"إضافة الهدف", addTheInjury:"إضافة الإصابة", addTheSubstitution:"إضافة التغيير", refereeCentral:"الحكم الرئيسي", assistant1:"الحكم المساعد الأول", assistant2:"الحكم المساعد الثاني", fourthOfficial:"الحكم الرابع", delegate:"المندوب الرئيسي", officialsValid:"تم اعتماد جميع الخطط الإجبارية.", officialsRequired:"يجب اعتماد الخطط الإجبارية قبل تأكيد ما قبل المباراة.", officialNameRequired:"اسم المسؤول مطلوب.", validatedAgain:"معتمد — إعادة الاعتماد", save:"حفظ", validate:"تأكيد", confirmError:"حدث خطأ أثناء التأكيد.", addError:"حدث خطأ أثناء الإضافة.", deleteError:"حدث خطأ أثناء الحذف.", validationError:"حدث خطأ أثناء التحقق.", closeSheetConfirm:"إغلاق ورقة المباراة؟ هذا الإجراء نهائي.", closeError:"حدث خطأ أثناء إغلاق الورقة.",
    draft:"مسودة", preSigned:"تم إمضاء ما قبل المباراة", inProgress:"المباراة جارية", postSigned:"تم إمضاء ما بعد المباراة", closed:"الورقة مغلقة",
    preSignatures:"إمضاءات ما قبل المباراة", postSignatures:"إمضاءات ما بعد المباراة", signaturesCompletePre:"تم جمع الإمضاءات الثلاثة قبل المباراة.", signaturesCompletePost:"تم جمع الإمضاءات الثلاثة بعد المباراة.", preConfirmed:"تم تأكيد ما قبل المباراة", waitingSignatures:"في انتظار الإمضاءات الثلاثة لبدء المباراة.", reservationsPre:"احترازات ما قبل المباراة", reservationsPost:"احترازات ما بعد المباراة", signFirst:"يرجى الإمضاء داخل الإطار قبل التأكيد.", signatureSaved:"تم حفظ الإمضاء.", saveError:"حدث خطأ أثناء الحفظ.", signed:"تم الإمضاء", signedOn:"تم الإمضاء في {date}", signatureAlt:"إمضاء — {label}", edit:"تعديل", signerOptional:"اسم الممضي (اختياري)", cancel:"إلغاء", saving:"جار الحفظ...", validateSignature:"تأكيد الإمضاء", unsigned:"غير ممضى.", reservationRequired:"محتوى الاحتراز مطلوب.", noReservation:"لا توجد احترازات مسجلة.", delete:"حذف", author:"صاحب الاحتراز", homeTeam:"الفريق المضيف", awayTeam:"الفريق الضيف", referee:"الحكم", reservationContent:"محتوى الاحتراز",
  }
} as const;
export type TranslationKey = keyof typeof dictionaries.fr;
export function translate(lang:"fr"|"ar", key:TranslationKey, values?:Record<string,string|number>) { let text:string=dictionaries[lang][key]; for(const [k,v] of Object.entries(values??{})) text=text.replaceAll(`{${k}}`,String(v)); return text; }
