import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { getStaffContractBundleForClub, updateStaffContractForClub } from "@/services/StaffContractService";
import { STAFF_CONTRACT_ROLES, StaffContractWorkflowError, type StaffContractRole } from "../../../../../../../../packages/regulatory-shared/src/staffContract";
export const runtime = "nodejs";
const actor = (request: NextRequest, user: { id: string; role: string }) => ({ userId: user.id, role: user.role, ipAddress: request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null, userAgent: request.headers.get("user-agent") });
const input = (body: Record<string, unknown>) => ({ staffId: String(body.staffId), seasonId: String(body.seasonId), role: body.role as StaffContractRole, startDate: String(body.startDate), endDate: String(body.endDate), salary: body.salary ? String(body.salary) : null, currency: body.currency ? String(body.currency) : null, qualificationId: body.qualificationId ? String(body.qualificationId) : null });
export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const session = await auth(); if (!session?.user.teamId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { return NextResponse.json(await getStaffContractBundleForClub(session.user.teamId, (await params).id)); } catch (error) { if (error instanceof StaffContractWorkflowError) return NextResponse.json({ error: error.message }, { status: 404 }); return NextResponse.json({ error: "Erreur serveur" }, { status: 500 }); } }
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const session = await auth(); if (!session?.user.teamId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!["ADMIN", "CLUB_ADMIN"].includes(session.user.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); try { const body = await request.json() as Record<string, unknown>; if (!body.staffId || !body.seasonId || !body.role || !body.startDate || !body.endDate || !STAFF_CONTRACT_ROLES.includes(body.role as StaffContractRole)) return NextResponse.json({ error: "Données de contrat incomplètes" }, { status: 400 }); return NextResponse.json(await updateStaffContractForClub(session.user.teamId, (await params).id, input(body), actor(request, session.user))); } catch (error) { if (error instanceof StaffContractWorkflowError) return NextResponse.json({ error: error.message }, { status: 409 }); return NextResponse.json({ error: "Erreur serveur" }, { status: 500 }); } }
