export const dictionaries = {
  fr: {
    "language.label": "Langue du site", "site.title": "Billetterie", "site.description": "Achetez vos billets pour les matchs de votre club",
    "common.allMatches": "← Tous les matchs", "common.dateTbc": "Date à confirmer", "common.vs": "vs", "common.reference": "Réf.",
    "home.subtitle": "Achetez vos billets pour les prochains matchs — tous clubs confondus.", "home.empty": "Aucune vente de billets n’est ouverte pour le moment.",
    "match.noOffers": "Aucune catégorie de billet n’est ouverte pour ce match.", "match.remaining": "{count} place(s) restante(s)",
    "match.homeOnly": "réservé aux supporters du club recevant", "match.awayOnly": "réservé aux supporters du club visiteur", "match.login": "Se connecter pour acheter",
    "purchase.saleClosed": "Vente non ouverte pour cette catégorie.", "purchase.soldOut": "Complet.", "purchase.homeConfirmation": "Je confirme être supporter du club recevant pour cette catégorie.", "purchase.awayConfirmation": "Je confirme être supporter du club visiteur pour cette catégorie.", "purchase.buy": "Acheter — {price}", "purchase.unexpected": "Réponse inattendue du serveur (lien de paiement manquant).", "purchase.failed": "Achat impossible.",
    "tickets.title": "Mes billets", "tickets.empty": "Vous n’avez encore acheté aucun billet.", "status.pending": "En attente", "status.paid": "Payé", "status.cancelled": "Annulé", "status.used": "Utilisé",
    "payment.invalid": "Lien de retour invalide", "payment.confirmed": "Paiement confirmé", "payment.available": "Vos billets sont disponibles dans « Mes billets ».", "payment.failed": "Paiement échoué ou annulé", "payment.released": "Votre réservation a été libérée. Vous pouvez retenter l’achat depuis la page du match.", "payment.checking": "Paiement en cours de vérification", "payment.wait": "Le statut définitif peut prendre quelques instants. Consultez « Mes billets » dans peu de temps.", "payment.viewTickets": "Voir mes billets",
    "admin.title": "Signal d’audience", "admin.description": "Billets dont l’audience déclarée ne correspond pas aux affiliations SSO de l’acheteur. Ce signal de modération ne bloque pas l’achat ; examinez le cas puis marquez-le comme traité.", "admin.home": "Domicile", "admin.away": "Visiteurs", "admin.public": "Public", "admin.empty": "Aucun signal en attente.", "admin.failed": "Échec du traitement.", "admin.audience": "Audience déclarée :", "admin.boughtOn": "acheté le", "admin.dismiss": "Marquer traité",
    "scanner.camera.unavailable": "Caméra non disponible sur cet appareil ou navigateur.", "scanner.camera.denied": "Accès à la caméra refusé ou indisponible.", "scanner.camera.fallback": "Utilisez la douchette ou la saisie manuelle ci-dessous.", "scanner.camera.starting": "Démarrage de la caméra…", "scanner.camera.use": "Utiliser la caméra", "scanner.camera.close": "Fermer la caméra",
    "scanner.network.online": "Connecté", "scanner.network.offline": "Hors connexion",
    "scanner.offline.enable": "Mode hors-ligne", "scanner.offline.enabled": "Mode hors-ligne activé", "scanner.offline.explanation": "Téléchargez la liste des billets du match pendant que vous êtes encore connecté. Les scans faits hors-ligne sont mis en file et devront être synchronisés dès que la connexion revient — un jeton forgé accepté hors-ligne peut être rejeté à la synchronisation.", "scanner.offline.manifestRequired": "Téléchargez d’abord la liste hors-ligne pour ce match.",
    "scanner.manifest.loaded": "Liste chargée : {match} ({count} billet(s), {date})", "scanner.manifest.forget": "Oublier cette liste", "scanner.manifest.noMatch": "Aucun match ouvert", "scanner.manifest.downloading": "Téléchargement…", "scanner.manifest.download": "Télécharger la liste hors-ligne", "scanner.manifest.downloadFailed": "Échec du téléchargement.",
    "scanner.sync.pending": "{count} scan(s) en attente de synchronisation", "scanner.sync.syncing": "Synchronisation…", "scanner.sync.action": "Synchroniser", "scanner.sync.success": "{count} scan(s) synchronisé(s).", "scanner.sync.failed": "{synced} scan(s) synchronisé(s), {failed} échec(s) — reste en file, réessayez.",
    "scanner.result.success": "Accès autorisé", "scanner.result.alreadyUsed": "Déjà scanné", "scanner.result.notPaid": "Billet non payé ou annulé", "scanner.result.matchCancelled": "Match annulé", "scanner.result.invalid": "Jeton invalide", "scanner.result.scanFailed": "Échec du scan.", "scanner.result.placeholder": "Scanner ou coller le contenu du QR code…", "scanner.result.submit": "Valider", "scanner.result.reference": "Réf.", "scanner.result.usedAt": "Déjà scanné le {date}",
    "scanner.history.title": "Derniers scans", "scanner.history.empty": "Aucun scan pour l’instant.", "scanner.history.you": "vous", "scanner.history.youOffline": "vous (hors-ligne, à synchroniser)", "scanner.history.now": "à l’instant",
    "team.home": "Équipe à domicile", "team.away": "Équipe visiteuse"
  },
  ar: {
    "language.label": "لغة الموقع", "site.title": "التذاكر", "site.description": "اشتر تذاكر مباريات ناديك",
    "common.allMatches": "جميع المباريات →", "common.dateTbc": "سيتم تحديد الموعد", "common.vs": "ضد", "common.reference": "المرجع",
    "home.subtitle": "اشتر تذاكر المباريات القادمة لجميع الأندية.", "home.empty": "لا توجد مبيعات تذاكر مفتوحة حاليا.",
    "match.noOffers": "لا توجد فئة تذاكر مفتوحة لهذه المباراة.", "match.remaining": "الأماكن المتبقية: {count}",
    "match.homeOnly": "مخصصة لجماهير الفريق المضيف", "match.awayOnly": "مخصصة لجماهير الفريق الضيف", "match.login": "سجّل الدخول للشراء",
    "purchase.saleClosed": "البيع غير مفتوح لهذه الفئة.", "purchase.soldOut": "نفدت التذاكر.", "purchase.homeConfirmation": "أؤكد أنني من جماهير الفريق المضيف لهذه الفئة.", "purchase.awayConfirmation": "أؤكد أنني من جماهير الفريق الضيف لهذه الفئة.", "purchase.buy": "شراء — {price}", "purchase.unexpected": "استجابة غير متوقعة من الخادم (رابط الدفع مفقود).", "purchase.failed": "تعذر الشراء.",
    "tickets.title": "تذاكري", "tickets.empty": "لم تشتر أي تذكرة بعد.", "status.pending": "في الانتظار", "status.paid": "مدفوع", "status.cancelled": "ملغى", "status.used": "مستعمل",
    "payment.invalid": "رابط العودة غير صالح", "payment.confirmed": "تم تأكيد الدفع", "payment.available": "تذاكرك متوفرة في «تذاكري».", "payment.failed": "فشل الدفع أو تم إلغاؤه", "payment.released": "تم تحرير حجزك. يمكنك إعادة محاولة الشراء من صفحة المباراة.", "payment.checking": "جار التحقق من الدفع", "payment.wait": "قد يستغرق تحديد الحالة النهائية بعض الوقت. راجع «تذاكري» بعد قليل.", "payment.viewTickets": "عرض تذاكري",
    "admin.title": "تنبيه الجمهور", "admin.description": "تذاكر لا يتطابق فيها الجمهور المصرح به مع انتماءات المشتري في نظام الدخول الموحد. لا يمنع تنبيه الإشراف عملية الشراء؛ راجع الحالة ثم علّمها كمعالجة.", "admin.home": "المضيف", "admin.away": "الزوار", "admin.public": "العموم", "admin.empty": "لا توجد تنبيهات معلقة.", "admin.failed": "فشلت المعالجة.", "admin.audience": "الجمهور المصرح به:", "admin.boughtOn": "تم الشراء في", "admin.dismiss": "تعليم كمعالج",
    "scanner.camera.unavailable": "الكاميرا غير متاحة على هذا الجهاز أو المتصفح.", "scanner.camera.denied": "تم رفض الوصول إلى الكاميرا أو أنها غير متاحة.", "scanner.camera.fallback": "استخدم قارئ الرموز أو الإدخال اليدوي أدناه.", "scanner.camera.starting": "جارٍ تشغيل الكاميرا…", "scanner.camera.use": "استخدام الكاميرا", "scanner.camera.close": "إغلاق الكاميرا",
    "scanner.network.online": "متصل", "scanner.network.offline": "غير متصل",
    "scanner.offline.enable": "وضع عدم الاتصال", "scanner.offline.enabled": "وضع عدم الاتصال مفعّل", "scanner.offline.explanation": "نزّل قائمة تذاكر المباراة بينما لا تزال متصلاً. تُضاف عمليات المسح دون اتصال إلى قائمة انتظار ويجب مزامنتها عند عودة الاتصال — وقد يُرفض أثناء المزامنة رمز مزوّر قُبل دون اتصال.", "scanner.offline.manifestRequired": "نزّل أولاً قائمة عدم الاتصال لهذه المباراة.",
    "scanner.manifest.loaded": "تم تحميل القائمة: {match} ({count} تذكرة، {date})", "scanner.manifest.forget": "حذف هذه القائمة", "scanner.manifest.noMatch": "لا توجد مباراة مفتوحة", "scanner.manifest.downloading": "جارٍ التنزيل…", "scanner.manifest.download": "تنزيل قائمة عدم الاتصال", "scanner.manifest.downloadFailed": "فشل التنزيل.",
    "scanner.sync.pending": "{count} عملية مسح في انتظار المزامنة", "scanner.sync.syncing": "جارٍ المزامنة…", "scanner.sync.action": "مزامنة", "scanner.sync.success": "تمت مزامنة {count} عملية مسح.", "scanner.sync.failed": "تمت مزامنة {synced} عملية مسح، وفشلت {failed} — بقيت في قائمة الانتظار، أعد المحاولة.",
    "scanner.result.success": "الدخول مسموح", "scanner.result.alreadyUsed": "تم مسح التذكرة مسبقاً", "scanner.result.notPaid": "التذكرة غير مدفوعة أو ملغاة", "scanner.result.matchCancelled": "المباراة ملغاة", "scanner.result.invalid": "الرمز غير صالح", "scanner.result.scanFailed": "فشل مسح التذكرة.", "scanner.result.placeholder": "امسح رمز QR أو الصق محتواه…", "scanner.result.submit": "تحقق", "scanner.result.reference": "المرجع", "scanner.result.usedAt": "تم مسحها مسبقاً في {date}",
    "scanner.history.title": "آخر عمليات المسح", "scanner.history.empty": "لا توجد عمليات مسح حتى الآن.", "scanner.history.you": "أنت", "scanner.history.youOffline": "أنت (دون اتصال، بانتظار المزامنة)", "scanner.history.now": "الآن",
    "team.home": "الفريق المضيف", "team.away": "الفريق الضيف"
  }
} as const;
export type TranslationKey = keyof typeof dictionaries.fr;
export type TranslationValues = Record<string, string | number>;
export function translate(locale: keyof typeof dictionaries, key: TranslationKey, values?: TranslationValues): string {
  let message: string = dictionaries[locale][key] ?? dictionaries.fr[key];
  for (const [name, value] of Object.entries(values ?? {})) message = message.replaceAll(`{${name}}`, String(value));
  return message;
}
