import { redirect } from 'next/navigation';
import { can, getUserAccess } from '@/lib/access';
import { listSellerApplicationsForClub } from '@/lib/marketplaceApiClient';
import { requireTeamId } from '@/lib/team-context';
import { MarketplaceAdminNav } from '../MarketplaceAdminNav';
import { approveSellerApplicationAction, markSellerApplicationReview, rejectSellerApplicationAction } from './actions';

export const dynamic = 'force-dynamic';
export default async function SellerApplicationsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const access = await getUserAccess(); if (!can(access, 'marketplace.moderate')) redirect('/admin'); const teamId = await requireTeamId(); const params = await searchParams; const applications = await listSellerApplicationsForClub(teamId, params.status || undefined);
  return <div className="container-fluid px-0"><h1 className="h4 mb-3">Demandes vendeurs</h1><MarketplaceAdminNav/><form className="mb-3"><select className="form-select form-select-sm" style={{maxWidth:240}} name="status" defaultValue={params.status ?? ''}><option value="">Tous les statuts</option>{['PENDING','UNDER_REVIEW','APPROVED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select></form><div className="card"><div className="card-body table-responsive"><table className="table align-middle"><thead><tr><th>Entreprise</th><th>Responsable</th><th>Contact</th><th>Justificatifs</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{applications.map(a=><tr key={a.id}><td><strong>{a.businessName}</strong><div className="text-muted small">{a.activityCategory || '—'}</div></td><td>{a.ownerName}</td><td>{a.email}<div className="small">{a.phone || ''}</div></td><td>{a.documents?.length ? a.documents.map(d=><div key={d.url}><a href={d.url} target="_blank" rel="noreferrer">{d.label}</a></div>) : '—'}</td><td>{a.status}{a.rejectionReason && <div className="text-danger small">{a.rejectionReason}</div>}</td><td><div className="d-flex flex-column gap-2">{a.status==='PENDING'&&<form action={markSellerApplicationReview.bind(null,a.id)}><button className="btn btn-outline-secondary btn-sm">Étudier</button></form>}{['PENDING','UNDER_REVIEW'].includes(a.status)&&<form action={approveSellerApplicationAction.bind(null,a.id)}><button className="btn btn-success btn-sm">Approuver</button></form>}{['PENDING','UNDER_REVIEW'].includes(a.status)&&<form action={rejectSellerApplicationAction.bind(null,a.id)} className="d-flex gap-1"><input name="reason" required className="form-control form-control-sm" placeholder="Motif"/><button className="btn btn-danger btn-sm">Refuser</button></form>}</div></td></tr>)}</tbody></table>{applications.length===0&&<p className="text-muted mb-0">Aucune demande.</p>}</div></div></div>;
}
