import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { getPlayerContractBundleForClub, updatePlayerContractForClub } from "@/services/PlayerContractService";
import { PLAYER_CONTRACT_TYPES, PlayerContractWorkflowError, type PlayerContractType } from "../../../../../../../../packages/regulatory-shared/src/playerContract";

export const runtime = "nodejs";
const actor = (request: NextRequest, user: { id: string; role: string }) => ({ userId: user.id, role: user.role, ipAddress: request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null, userAgent: request.headers.get("user-agent") });
export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const session = await auth(); if (!session?.user.teamId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const { id } = await params; return NextResponse.json(await getPlayerContractBundleForClub(session.user.teamId, id)); } catch (error) { if (error instanceof PlayerContractWorkflowError) return NextResponse.json({ error: error.message }, { status: 404 }); return NextResponse.json({ error: "Erreur serveur" }, { status: 500 }); } }
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const session = await auth(); if (!session?.user.teamId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!["ADMIN", "CLUB_ADMIN"].includes(session.user.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); try { const { id } = await params; const body = await request.json() as Record<string, unknown>; if (!body.playerId || !body.seasonId || !body.contractType || !body.startDate || !body.endDate || !PLAYER_CONTRACT_TYPES.includes(body.contractType as PlayerContractType)) return NextResponse.json({ error: "Données de contrat incomplètes" }, { status: 400 }); return NextResponse.json(await updatePlayerContractForClub(session.user.teamId, id, { playerId: String(body.playerId), seasonId: String(body.seasonId), contractType: body.contractType as PlayerContractType, startDate: String(body.startDate), endDate: String(body.endDate), salary: body.salary ? String(body.salary) : null, currency: body.currency ? String(body.currency) : null, agentId: body.agentId ? String(body.agentId) : null, bonusesJson: body.bonusesJson && typeof body.bonusesJson === "object" ? body.bonusesJson as Record<string, unknown> : null }, actor(request, session.user))); } catch (error) { if (error instanceof PlayerContractWorkflowError) return NextResponse.json({ error: error.message }, { status: 409 }); return NextResponse.json({ error: "Erreur serveur" }, { status: 500 }); } }
