"use client";
import { useState } from "react";
type Assignment={id:string;matchId:string;teamId:string;staffId:string;role:string};
export default function MatchStaffManager(){
 const [matchId,setMatchId]=useState("");const [items,setItems]=useState<Assignment[]>([]);const [staffId,setStaffId]=useState("");const [role,setRole]=useState("HEAD_COACH");const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 async function load(){if(!matchId)return;try{const r=await fetch(`/api/admin/federation/match-staff?matchId=${encodeURIComponent(matchId)}`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error??"Erreur");setItems(b)}catch(e){setError(e instanceof Error?e.message:"Erreur")}}
 async function assign(){if(!matchId||!staffId)return;setSaving(true);try{const r=await fetch("/api/admin/federation/match-staff",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({matchId,staffId,role})});const b=await r.json();if(!r.ok)throw new Error(b.error??"Erreur");setStaffId("");await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}}
 async function remove(id:string){setSaving(true);try{const r=await fetch("/api/admin/federation/match-staff",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});const b=await r.json();if(!r.ok)throw new Error(b.error??"Erreur");await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}}
 return <div className="container-fluid px-0 d-flex flex-column gap-3"><div><h1 className="h4 mb-1">Staff officiel du match</h1><p className="text-muted mb-0">Affectez notamment l’entraîneur principal. Sa qualification CAF sera contrôlée avant la validation officielle de la feuille.</p></div>{error&&<div className="alert alert-danger" onClick={()=>setError("")}>{error}</div>}<div className="card border-0 shadow-sm"><div className="card-body row g-2"><div className="col-md-9"><label className="form-label">Match</label><input className="form-control" placeholder="matchId" value={matchId} onChange={e=>setMatchId(e.target.value)}/></div><div className="col-md-3 d-flex align-items-end"><button className="btn btn-outline-primary w-100" disabled={!matchId} onClick={()=>void load()}>Charger</button></div></div></div>{matchId&&<div className="card border-0 shadow-sm"><div className="card-header">Nouvelle affectation</div><div className="card-body row g-2"><div className="col-md-6"><label className="form-label">Membre du staff</label><input className="form-control" placeholder="staffId" value={staffId} onChange={e=>setStaffId(e.target.value)}/></div><div className="col-md-4"><label className="form-label">Rôle officiel</label><select className="form-select" value={role} onChange={e=>setRole(e.target.value)}><option>HEAD_COACH</option><option>ASSISTANT_COACH</option><option>MEDICAL</option><option>STAFF</option></select></div><div className="col-md-2 d-flex align-items-end"><button className="btn btn-primary w-100" disabled={saving||!staffId} onClick={()=>void assign()}>Affecter</button></div></div></div>}<div className="card border-0 shadow-sm"><div className="table-responsive"><table className="table mb-0"><thead><tr><th>Staff</th><th>Rôle</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.staffId}</td><td><span className={x.role==="HEAD_COACH"?"badge bg-primary":"badge bg-secondary"}>{x.role}</span></td><td className="text-end"><button className="btn btn-sm btn-outline-danger" disabled={saving} onClick={()=>void remove(x.id)}>Retirer</button></td></tr>)}</tbody></table></div></div></div>
}
