import { getEffectiveLicenseStatus, getLicenseRoleLabel, getLicenseStatusLabel, type LicenseCardLocale, type PersonLicenseCardRecord } from "../../../../packages/regulatory-shared/src/licenseCard";

const COLORS: Record<string, { background: string; color: string }> = { APPROVED: { background: "#d1fae5", color: "#065f46" }, SUSPENDED: { background: "#fef3c7", color: "#92400e" }, EXPIRED: { background: "#e5e7eb", color: "#374151" }, REVOKED: { background: "#fee2e2", color: "#991b1b" }, REJECTED: { background: "#fee2e2", color: "#991b1b" }, UNDER_REVIEW: { background: "#dbeafe", color: "#1e40af" }, SUBMITTED: { background: "#cffafe", color: "#155e75" }, DRAFT: { background: "#f3f4f6", color: "#4b5563" } };

export function FederationLicenseCard({ license, holderName, locale = "fr" }: { license: PersonLicenseCardRecord; holderName: string; locale?: LicenseCardLocale }) {
  const state = getEffectiveLicenseStatus(license.status, license.expiresAt); const status = getLicenseStatusLabel(license.status, license.expiresAt, locale); const code = license.federationCode || "FTF"; const rtl = locale === "ar"; const federation = license.federationName || (rtl ? "الجامعة التونسية لكرة القدم" : "Fédération Tunisienne de Football");
  return <article dir={rtl ? "rtl" : "ltr"} style={{ width: "100%", maxWidth: 430, position: "relative", overflow: "hidden", borderRadius: 26, color: "#fff", background: "linear-gradient(145deg,#061d2d,#031522 58%,#081d2c)", border: "1px solid rgba(255,255,255,.12)", boxShadow: "0 20px 55px rgba(3,21,34,.22)" }}>
    <div style={{ height: 7, background: "#e30613" }} /><div style={{ padding: "22px 26px 20px" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 12, minWidth: 0 }}>{license.federationLogoUrl ? <>{/* eslint-disable-next-line @next/next/no-img-element */}<img src={license.federationLogoUrl} alt={federation} width={64} height={64} style={{ width: 64, height: 64, borderRadius: "50%", objectFit: "contain", background: "#fff", padding: 5 }} /></> : <div style={{ width: 64, height: 64, borderRadius: "50%", border: "4px solid #e30613", background: "#fff", display: "grid", placeItems: "center", color: "#e30613", fontWeight: 900 }}>{code}</div>}<div><div style={{ fontSize: 11, color: "#a9bdca", fontWeight: 700 }}>{rtl ? "وثيقة رسمية" : "DOCUMENT OFFICIEL"}</div><div style={{ fontSize: 13, color: "#e7eef2" }}>{federation}</div></div></div><span style={{ ...(COLORS[state] ?? COLORS.DRAFT), borderRadius: 999, padding: "6px 10px", fontSize: 11, fontWeight: 800 }}>{status}</span></div>
      <div style={{ fontSize: 34, marginTop: 24, letterSpacing: "-.025em" }}>{rtl ? `ترخيص ${code}` : `Licence ${code}`}</div><div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) auto", gap: 20, marginTop: 25, alignItems: "end" }}><div><div style={{ fontSize: 14, color: "#d0dde5" }}>{getLicenseRoleLabel(license.personType, locale)}</div><div style={{ fontSize: 22, fontWeight: 750 }}>{holderName}</div></div><div style={{ textAlign: rtl ? "left" : "right" }}><div style={{ fontSize: 12, color: "#d0dde5" }}>{rtl ? "الموسم" : "SAISON"}</div><div style={{ fontSize: 18, fontWeight: 750 }}>{license.seasonName || "—"}</div></div></div>
      <div style={{ height: 1, background: "rgba(255,255,255,.16)", margin: "22px 0 18px" }} /><div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(130px,.75fr)", gap: 20 }}><div><div style={{ fontSize: 12, color: "#a9bdca" }}>{rtl ? "النادي" : "CLUB"}</div><div style={{ fontSize: 17, fontWeight: 750 }}>{license.clubName || (rtl ? "دون ناد" : "Sans club")}</div></div><div style={{ textAlign: rtl ? "left" : "right" }}><div style={{ fontSize: 12, color: "#a9bdca" }}>{rtl ? "رقم الترخيص" : "N° de licencié(e)"}</div><div style={{ fontSize: 19, fontWeight: 800, overflowWrap: "anywhere" }}>{license.licenseNumber || "—"}</div></div></div><div style={{ marginTop: 16, display: "flex", gap: 8, flexWrap: "wrap" }}>{license.category && <span style={{ fontSize: 11, padding: "5px 8px", borderRadius: 999, background: "rgba(255,255,255,.09)" }}>{license.category}</span>}<span style={{ fontSize: 11, padding: "5px 8px", borderRadius: 999, background: "rgba(255,255,255,.09)" }}>{license.licenseType}</span></div></div>
    <div style={{ minHeight: 70, background: "linear-gradient(100deg,#d90012,#ef0718)", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 24px", gap: 14 }}><div style={{ display: "flex", alignItems: "center", gap: 9 }}><div style={{ width: 38, height: 38, borderRadius: "50%", background: "#fff", color: "#e30613", display: "grid", placeItems: "center", fontWeight: 900 }}>★</div><div><strong style={{ fontSize: 12 }}>{code}</strong><div style={{ fontSize: 10 }}>{rtl ? "بطاقة رقمية اتحادية" : "Carte fédérale numérique"}</div></div></div><div style={{ fontSize: 10, opacity: .85 }}>{rtl ? "الحالة الفعلية في النظام" : "Statut réglementaire en temps réel"}</div></div>{state !== "APPROVED" && <div aria-hidden style={{ position: "absolute", left: "50%", top: "46%", transform: "translate(-50%,-50%) rotate(-12deg)", border: "3px solid rgba(255,255,255,.16)", color: "rgba(255,255,255,.18)", borderRadius: 8, padding: "8px 15px", fontSize: 25, fontWeight: 900, whiteSpace: "nowrap" }}>{status.toUpperCase()}</div>}
  </article>;
}
