export enum NotificationType {
  PRODUCT_APPROVED = 'PRODUCT_APPROVED',
  PRODUCT_REJECTED = 'PRODUCT_REJECTED',
  SELLER_ACTIVATED = 'SELLER_ACTIVATED',
  SELLER_SUSPENDED = 'SELLER_SUSPENDED',
  NEW_ORDER = 'NEW_ORDER',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  PAYOUT_PAID = 'PAYOUT_PAID',
  LOW_STOCK = 'LOW_STOCK',
}
