import { describe, expect, it } from "vitest";
import { assertStaffContractDates, assertStaffContractFederalTransition, assertStaffContractSubmittable, assertStaffContractTransition, canEditStaffContract, isStaffContractEligible } from "../../../packages/regulatory-shared/src/staffContract";
describe("staff contract domain", () => {
  it("accepts the club and federal happy paths", () => { expect(() => assertStaffContractTransition("DRAFT", "SIGNED")).not.toThrow(); expect(() => assertStaffContractFederalTransition("NOT_SUBMITTED", "SUBMITTED")).not.toThrow(); expect(() => assertStaffContractFederalTransition("SUBMITTED", "UNDER_REVIEW")).not.toThrow(); expect(() => assertStaffContractFederalTransition("UNDER_REVIEW", "APPROVED")).not.toThrow(); });
  it("rejects shortcut transitions", () => { expect(() => assertStaffContractTransition("DRAFT", "TERMINATED")).toThrow(); expect(() => assertStaffContractFederalTransition("SUBMITTED", "APPROVED")).toThrow(); });
  it("requires coherent dates, signature and a current document", () => { expect(() => assertStaffContractDates("2027-01-01", "2026-12-31")).toThrow(); expect(() => assertStaffContractSubmittable("DRAFT", true)).toThrow(); expect(() => assertStaffContractSubmittable("SIGNED", false)).toThrow(); expect(() => assertStaffContractSubmittable("SIGNED", true)).not.toThrow(); });
  it("requires an active qualification when configured", () => { const base = { status: "SIGNED" as const, federalStatus: "APPROVED" as const, endDate: "2027-06-30", requiresQualification: true }; expect(isStaffContractEligible({ ...base, qualificationStatus: "APPROVED", qualificationExpiresAt: "2027-06-30" }, new Date("2026-08-14"))).toBe(true); expect(isStaffContractEligible({ ...base, qualificationStatus: "SUSPENDED", qualificationExpiresAt: "2027-06-30" }, new Date("2026-08-14"))).toBe(false); });
  it("allows eligibility without qualification when the competition does not require it", () => { expect(isStaffContractEligible({ status: "SIGNED", federalStatus: "APPROVED", endDate: "2027-06-30", requiresQualification: false }, new Date("2026-08-14"))).toBe(true); expect(canEditStaffContract("SIGNED", "SUBMITTED")).toBe(false); });
});
